### ISSUE TITLE
Key error when execute prediction

### ISSUE THREAD

**Issue by secsilm** [eisenjulian/nlp_estimator_tutorial#3]
First thank you for your execellent tutorial. 

I met a KerError when I run the [`nlp_estimators.py`](https://github.com/eisenjulian/nlp_estimator_tutorial/blob/master/nlp_estimators.py) at [L140](https://github.com/eisenjulian/nlp_estimator_tutorial/blob/33659a5ce4aa3f4b5c35664ac15d7e352c5e6f20/nlp_estimators.py#L140), which said it cannot find the key `logistic`:

```python
predictions = np.array([p['logistic'][0] for p in classifier.predict(input_fn=eval_input_fn)])
```

I'm using TensorFlow 1.9. Is it supposed to be `probabilities`?

**Comment by eisenjulian** [comment]
Hello @secsilm it might be that the API has changed since we wrote this, but I couldn't reproduce the issue in tf v1.10, can you? If we change it to use the `probabilities` we should get the second element from the array since that's the one that matches with the `logistic` score.
